twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        routes: '@App\Provider\FrontendRoutesProvider'
        globals: '@App\Provider\FrontendGlobalsProvider'
